// Mock data for Quality Maturity Index Dashboard

export interface KPI {
  id: string;
  name: string;
  value: number;
  target: number;
  unit: string;
  trend: 'up' | 'down' | 'stable';
  trendValue: number;
  status: 'good' | 'warning' | 'critical';
  history: { month: string; value: number }[];
}

export interface CategoryData {
  id: string;
  name: string;
  score: number;
  weight: number;
  kpis: KPI[];
  description: string;
}

export const categories: CategoryData[] = [
  {
    id: 'stability',
    name: 'Functional Stability',
    score: 82,
    weight: 20,
    description: 'Measures how consistently features behave without failures across global agency usage.',
    kpis: [
      {
        id: 'feature-failure',
        name: 'Feature Failure Rate',
        value: 2.3,
        target: 3.0,
        unit: '%',
        trend: 'down',
        trendValue: 0.5,
        status: 'good',
        history: [
          { month: 'Jan', value: 3.2 },
          { month: 'Feb', value: 3.0 },
          { month: 'Mar', value: 2.8 },
          { month: 'Apr', value: 2.5 },
          { month: 'May', value: 2.3 },
        ],
      },
      {
        id: 'stability-index',
        name: 'Stability Index',
        value: 99.7,
        target: 99.5,
        unit: '%',
        trend: 'up',
        trendValue: 0.2,
        status: 'good',
        history: [
          { month: 'Jan', value: 99.3 },
          { month: 'Feb', value: 99.4 },
          { month: 'Mar', value: 99.5 },
          { month: 'Apr', value: 99.6 },
          { month: 'May', value: 99.7 },
        ],
      },
      {
        id: 'api-error',
        name: 'API Error Rate',
        value: 1.8,
        target: 2.0,
        unit: '%',
        trend: 'down',
        trendValue: 0.3,
        status: 'good',
        history: [
          { month: 'Jan', value: 2.5 },
          { month: 'Feb', value: 2.3 },
          { month: 'Mar', value: 2.1 },
          { month: 'Apr', value: 1.9 },
          { month: 'May', value: 1.8 },
        ],
      },
      {
        id: 'rollback-count',
        name: 'Rollback/Hotfix Count',
        value: 3,
        target: 5,
        unit: 'count',
        trend: 'down',
        trendValue: 2,
        status: 'good',
        history: [
          { month: 'Jan', value: 7 },
          { month: 'Feb', value: 5 },
          { month: 'Mar', value: 4 },
          { month: 'Apr', value: 3 },
          { month: 'May', value: 3 },
        ],
      },
      {
        id: 'mtbf',
        name: 'Mean Time Between Failures',
        value: 168,
        target: 120,
        unit: 'hours',
        trend: 'up',
        trendValue: 12,
        status: 'good',
        history: [
          { month: 'Jan', value: 144 },
          { month: 'Feb', value: 152 },
          { month: 'Mar', value: 160 },
          { month: 'Apr', value: 165 },
          { month: 'May', value: 168 },
        ],
      },
      {
        id: 'requirements-coverage',
        name: 'Requirements Coverage Ratio',
        value: 94,
        target: 90,
        unit: '%',
        trend: 'up',
        trendValue: 3,
        status: 'good',
        history: [
          { month: 'Jan', value: 88 },
          { month: 'Feb', value: 90 },
          { month: 'Mar', value: 92 },
          { month: 'Apr', value: 93 },
          { month: 'May', value: 94 },
        ],
      },
      {
        id: 'test-coverage',
        name: 'Functional Test Coverage',
        value: 87,
        target: 85,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'good',
        history: [
          { month: 'Jan', value: 85 },
          { month: 'Feb', value: 86 },
          { month: 'Mar', value: 87 },
          { month: 'Apr', value: 87 },
          { month: 'May', value: 87 },
        ],
      },
      {
        id: 'booking-success',
        name: 'Booking Success Rate',
        value: 96.5,
        target: 95.0,
        unit: '%',
        trend: 'up',
        trendValue: 1.2,
        status: 'good',
        history: [
          { month: 'Jan', value: 94.8 },
          { month: 'Feb', value: 95.2 },
          { month: 'Mar', value: 95.8 },
          { month: 'Apr', value: 96.2 },
          { month: 'May', value: 96.5 },
        ],
      },
      {
        id: 'search-completeness',
        name: 'Search Result Completeness',
        value: 92,
        target: 90,
        unit: '%',
        trend: 'up',
        trendValue: 2,
        status: 'good',
        history: [
          { month: 'Jan', value: 88 },
          { month: 'Feb', value: 89 },
          { month: 'Mar', value: 90 },
          { month: 'Apr', value: 91 },
          { month: 'May', value: 92 },
        ],
      },
    ],
  },
  {
    id: 'defects',
    name: 'Defect Management',
    score: 75,
    weight: 20,
    description: 'Represents product quality in terms of bugs and incident patterns.',
    kpis: [
      {
        id: 'defect-density',
        name: 'Defect Density',
        value: 3.2,
        target: 4.0,
        unit: 'per module',
        trend: 'down',
        trendValue: 0.8,
        status: 'good',
        history: [
          { month: 'Jan', value: 5.0 },
          { month: 'Feb', value: 4.5 },
          { month: 'Mar', value: 4.0 },
          { month: 'Apr', value: 3.5 },
          { month: 'May', value: 3.2 },
        ],
      },
      {
        id: 'open-defects',
        name: 'Open Defects (Weighted)',
        value: 42,
        target: 50,
        unit: 'count',
        trend: 'down',
        trendValue: 8,
        status: 'warning',
        history: [
          { month: 'Jan', value: 58 },
          { month: 'Feb', value: 54 },
          { month: 'Mar', value: 48 },
          { month: 'Apr', value: 45 },
          { month: 'May', value: 42 },
        ],
      },
      {
        id: 'defect-leakage',
        name: 'Defect Leakage Rate',
        value: 12,
        target: 10,
        unit: '%',
        trend: 'up',
        trendValue: 2,
        status: 'warning',
        history: [
          { month: 'Jan', value: 8 },
          { month: 'Feb', value: 9 },
          { month: 'Mar', value: 10 },
          { month: 'Apr', value: 11 },
          { month: 'May', value: 12 },
        ],
      },
      {
        id: 'critical-defects',
        name: 'Critical & High Severity Defects',
        value: 8,
        target: 10,
        unit: 'count',
        trend: 'down',
        trendValue: 2,
        status: 'good',
        history: [
          { month: 'Jan', value: 12 },
          { month: 'Feb', value: 11 },
          { month: 'Mar', value: 10 },
          { month: 'Apr', value: 9 },
          { month: 'May', value: 8 },
        ],
      },
      {
        id: 'defect-reopen',
        name: 'Defect Reopen Rate',
        value: 15,
        target: 12,
        unit: '%',
        trend: 'up',
        trendValue: 3,
        status: 'warning',
        history: [
          { month: 'Jan', value: 10 },
          { month: 'Feb', value: 11 },
          { month: 'Mar', value: 13 },
          { month: 'Apr', value: 14 },
          { month: 'May', value: 15 },
        ],
      },
      {
        id: 'mttd',
        name: 'Mean Time to Detect',
        value: 48,
        target: 72,
        unit: 'hours',
        trend: 'down',
        trendValue: 12,
        status: 'good',
        history: [
          { month: 'Jan', value: 72 },
          { month: 'Feb', value: 65 },
          { month: 'Mar', value: 58 },
          { month: 'Apr', value: 52 },
          { month: 'May', value: 48 },
        ],
      },
      {
        id: 'mttr',
        name: 'Mean Time to Resolve',
        value: 96,
        target: 120,
        unit: 'hours',
        trend: 'down',
        trendValue: 18,
        status: 'good',
        history: [
          { month: 'Jan', value: 132 },
          { month: 'Feb', value: 120 },
          { month: 'Mar', value: 110 },
          { month: 'Apr', value: 102 },
          { month: 'May', value: 96 },
        ],
      },
      {
        id: 'regression-rate',
        name: 'Regression Issue Rate',
        value: 5,
        target: 8,
        unit: 'per cycle',
        trend: 'down',
        trendValue: 2,
        status: 'good',
        history: [
          { month: 'Jan', value: 9 },
          { month: 'Feb', value: 8 },
          { month: 'Mar', value: 7 },
          { month: 'Apr', value: 6 },
          { month: 'May', value: 5 },
        ],
      },
    ],
  },
  {
    id: 'performance',
    name: 'System Performance',
    score: 88,
    weight: 20,
    description: 'Critical for travel domain where search latency directly drives conversion.',
    kpis: [
      {
        id: 'page-load',
        name: 'Average Page Load Time',
        value: 1.8,
        target: 2.5,
        unit: 'seconds',
        trend: 'down',
        trendValue: 0.3,
        status: 'good',
        history: [
          { month: 'Jan', value: 2.4 },
          { month: 'Feb', value: 2.2 },
          { month: 'Mar', value: 2.0 },
          { month: 'Apr', value: 1.9 },
          { month: 'May', value: 1.8 },
        ],
      },
      {
        id: 'api-response',
        name: 'Average API Response Time',
        value: 320,
        target: 500,
        unit: 'ms',
        trend: 'down',
        trendValue: 80,
        status: 'good',
        history: [
          { month: 'Jan', value: 480 },
          { month: 'Feb', value: 420 },
          { month: 'Mar', value: 380 },
          { month: 'Apr', value: 350 },
          { month: 'May', value: 320 },
        ],
      },
      {
        id: 'p95-latency',
        name: 'P95 Latency',
        value: 850,
        target: 1000,
        unit: 'ms',
        trend: 'down',
        trendValue: 50,
        status: 'good',
        history: [
          { month: 'Jan', value: 1050 },
          { month: 'Feb', value: 980 },
          { month: 'Mar', value: 920 },
          { month: 'Apr', value: 880 },
          { month: 'May', value: 850 },
        ],
      },
      {
        id: 'throughput',
        name: 'Throughput (TPS)',
        value: 1250,
        target: 1000,
        unit: 'TPS',
        trend: 'up',
        trendValue: 150,
        status: 'good',
        history: [
          { month: 'Jan', value: 950 },
          { month: 'Feb', value: 1050 },
          { month: 'Mar', value: 1150 },
          { month: 'Apr', value: 1200 },
          { month: 'May', value: 1250 },
        ],
      },
      {
        id: 'error-rate-load',
        name: 'Error Rate under Load',
        value: 0.8,
        target: 1.5,
        unit: '%',
        trend: 'down',
        trendValue: 0.4,
        status: 'good',
        history: [
          { month: 'Jan', value: 1.6 },
          { month: 'Feb', value: 1.4 },
          { month: 'Mar', value: 1.2 },
          { month: 'Apr', value: 1.0 },
          { month: 'May', value: 0.8 },
        ],
      },
      {
        id: 'scalability',
        name: 'System Scalability Index',
        value: 92,
        target: 85,
        unit: '%',
        trend: 'up',
        trendValue: 5,
        status: 'good',
        history: [
          { month: 'Jan', value: 82 },
          { month: 'Feb', value: 85 },
          { month: 'Mar', value: 88 },
          { month: 'Apr', value: 90 },
          { month: 'May', value: 92 },
        ],
      },
      {
        id: 'cache-efficiency',
        name: 'Caching Efficiency',
        value: 78,
        target: 70,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'good',
        history: [
          { month: 'Jan', value: 76 },
          { month: 'Feb', value: 77 },
          { month: 'Mar', value: 78 },
          { month: 'Apr', value: 78 },
          { month: 'May', value: 78 },
        ],
      },
      {
        id: 'resource-utilization',
        name: 'Resource Utilization Health',
        value: 68,
        target: 80,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'good',
        history: [
          { month: 'Jan', value: 65 },
          { month: 'Feb', value: 66 },
          { month: 'Mar', value: 67 },
          { month: 'Apr', value: 68 },
          { month: 'May', value: 68 },
        ],
      },
    ],
  },
  {
    id: 'maintainability',
    name: 'Maintainability',
    score: 71,
    weight: 10,
    description: 'Indicates long-term product sustainability, code health, and ease of change.',
    kpis: [
      {
        id: 'code-complexity',
        name: 'Code Complexity Score',
        value: 15,
        target: 20,
        unit: 'avg complexity',
        trend: 'down',
        trendValue: 3,
        status: 'good',
        history: [
          { month: 'Jan', value: 21 },
          { month: 'Feb', value: 19 },
          { month: 'Mar', value: 17 },
          { month: 'Apr', value: 16 },
          { month: 'May', value: 15 },
        ],
      },
      {
        id: 'tech-debt',
        name: 'Technical Debt Ratio',
        value: 18,
        target: 15,
        unit: '%',
        trend: 'up',
        trendValue: 3,
        status: 'warning',
        history: [
          { month: 'Jan', value: 12 },
          { month: 'Feb', value: 14 },
          { month: 'Mar', value: 16 },
          { month: 'Apr', value: 17 },
          { month: 'May', value: 18 },
        ],
      },
      {
        id: 'auto-test-coverage',
        name: 'Automated Test Coverage',
        value: 72,
        target: 80,
        unit: '%',
        trend: 'up',
        trendValue: 5,
        status: 'warning',
        history: [
          { month: 'Jan', value: 62 },
          { month: 'Feb', value: 65 },
          { month: 'Mar', value: 68 },
          { month: 'Apr', value: 70 },
          { month: 'May', value: 72 },
        ],
      },
      {
        id: 'mttc',
        name: 'Mean Time to Implement Change',
        value: 72,
        target: 96,
        unit: 'hours',
        trend: 'down',
        trendValue: 12,
        status: 'good',
        history: [
          { month: 'Jan', value: 96 },
          { month: 'Feb', value: 88 },
          { month: 'Mar', value: 80 },
          { month: 'Apr', value: 76 },
          { month: 'May', value: 72 },
        ],
      },
      {
        id: 'refactoring',
        name: 'Refactoring Completion',
        value: 65,
        target: 80,
        unit: '%',
        trend: 'up',
        trendValue: 8,
        status: 'warning',
        history: [
          { month: 'Jan', value: 45 },
          { month: 'Feb', value: 50 },
          { month: 'Mar', value: 55 },
          { month: 'Apr', value: 60 },
          { month: 'May', value: 65 },
        ],
      },
      {
        id: 'code-review',
        name: 'Code Review Compliance',
        value: 88,
        target: 90,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'good',
        history: [
          { month: 'Jan', value: 85 },
          { month: 'Feb', value: 86 },
          { month: 'Mar', value: 87 },
          { month: 'Apr', value: 88 },
          { month: 'May', value: 88 },
        ],
      },
    ],
  },
  {
    id: 'operability',
    name: 'Operability',
    score: 79,
    weight: 10,
    description: 'Reflects how easily teams can operate, monitor, and support the product.',
    kpis: [
      {
        id: 'incident-volume',
        name: 'Incident Volume',
        value: 18,
        target: 25,
        unit: 'count/month',
        trend: 'down',
        trendValue: 5,
        status: 'good',
        history: [
          { month: 'Jan', value: 28 },
          { month: 'Feb', value: 25 },
          { month: 'Mar', value: 22 },
          { month: 'Apr', value: 20 },
          { month: 'May', value: 18 },
        ],
      },
      {
        id: 'mtta',
        name: 'Mean Time to Acknowledge',
        value: 12,
        target: 15,
        unit: 'minutes',
        trend: 'down',
        trendValue: 3,
        status: 'good',
        history: [
          { month: 'Jan', value: 18 },
          { month: 'Feb', value: 16 },
          { month: 'Mar', value: 14 },
          { month: 'Apr', value: 13 },
          { month: 'May', value: 12 },
        ],
      },
      {
        id: 'deployment-success',
        name: 'Deployment Success Rate',
        value: 94,
        target: 95,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'warning',
        history: [
          { month: 'Jan', value: 92 },
          { month: 'Feb', value: 93 },
          { month: 'Mar', value: 94 },
          { month: 'Apr', value: 94 },
          { month: 'May', value: 94 },
        ],
      },
      {
        id: 'monitoring-coverage',
        name: 'Monitoring Coverage Index',
        value: 85,
        target: 90,
        unit: '%',
        trend: 'up',
        trendValue: 5,
        status: 'warning',
        history: [
          { month: 'Jan', value: 75 },
          { month: 'Feb', value: 78 },
          { month: 'Mar', value: 80 },
          { month: 'Apr', value: 82 },
          { month: 'May', value: 85 },
        ],
      },
      {
        id: 'alert-noise',
        name: 'Alert Noise Ratio',
        value: 22,
        target: 15,
        unit: '%',
        trend: 'down',
        trendValue: 5,
        status: 'warning',
        history: [
          { month: 'Jan', value: 32 },
          { month: 'Feb', value: 28 },
          { month: 'Mar', value: 25 },
          { month: 'Apr', value: 24 },
          { month: 'May', value: 22 },
        ],
      },
      {
        id: 'sla-compliance',
        name: 'SLA Compliance',
        value: 96,
        target: 95,
        unit: '%',
        trend: 'up',
        trendValue: 1,
        status: 'good',
        history: [
          { month: 'Jan', value: 94 },
          { month: 'Feb', value: 95 },
          { month: 'Mar', value: 95 },
          { month: 'Apr', value: 96 },
          { month: 'May', value: 96 },
        ],
      },
    ],
  },
  {
    id: 'security',
    name: 'Security',
    score: 84,
    weight: 10,
    description: 'Critical for enterprise travel system handling PII and payment data.',
    kpis: [
      {
        id: 'vulnerability-density',
        name: 'Vulnerability Density',
        value: 2.1,
        target: 3.0,
        unit: 'per module',
        trend: 'down',
        trendValue: 0.6,
        status: 'good',
        history: [
          { month: 'Jan', value: 3.3 },
          { month: 'Feb', value: 2.9 },
          { month: 'Mar', value: 2.6 },
          { month: 'Apr', value: 2.3 },
          { month: 'May', value: 2.1 },
        ],
      },
      {
        id: 'patch-compliance',
        name: 'Patch Compliance',
        value: 92,
        target: 90,
        unit: '%',
        trend: 'up',
        trendValue: 3,
        status: 'good',
        history: [
          { month: 'Jan', value: 85 },
          { month: 'Feb', value: 87 },
          { month: 'Mar', value: 89 },
          { month: 'Apr', value: 90 },
          { month: 'May', value: 92 },
        ],
      },
      {
        id: 'security-test-coverage',
        name: 'Security Test Coverage',
        value: 78,
        target: 80,
        unit: '%',
        trend: 'up',
        trendValue: 5,
        status: 'warning',
        history: [
          { month: 'Jan', value: 68 },
          { month: 'Feb', value: 71 },
          { month: 'Mar', value: 74 },
          { month: 'Apr', value: 76 },
          { month: 'May', value: 78 },
        ],
      },
      {
        id: 'auth-failure',
        name: 'API Authentication Failure Rate',
        value: 0.3,
        target: 0.5,
        unit: '%',
        trend: 'down',
        trendValue: 0.1,
        status: 'good',
        history: [
          { month: 'Jan', value: 0.6 },
          { month: 'Feb', value: 0.5 },
          { month: 'Mar', value: 0.4 },
          { month: 'Apr', value: 0.3 },
          { month: 'May', value: 0.3 },
        ],
      },
      {
        id: 'privacy-compliance',
        name: 'Data Privacy Compliance Score',
        value: 95,
        target: 95,
        unit: '%',
        trend: 'stable',
        trendValue: 0,
        status: 'good',
        history: [
          { month: 'Jan', value: 93 },
          { month: 'Feb', value: 94 },
          { month: 'Mar', value: 95 },
          { month: 'Apr', value: 95 },
          { month: 'May', value: 95 },
        ],
      },
      {
        id: 'security-incidents',
        name: 'Security Incident Frequency',
        value: 1,
        target: 2,
        unit: 'count/month',
        trend: 'down',
        trendValue: 1,
        status: 'good',
        history: [
          { month: 'Jan', value: 3 },
          { month: 'Feb', value: 2 },
          { month: 'Mar', value: 2 },
          { month: 'Apr', value: 1 },
          { month: 'May', value: 1 },
        ],
      },
    ],
  },
];

export const qmiHistory = [
  { month: 'Jan', value: 74 },
  { month: 'Feb', value: 76 },
  { month: 'Mar', value: 77 },
  { month: 'Apr', value: 79 },
  { month: 'May', value: 80.5 },
];

export const calculateQMI = (): number => {
  return categories.reduce((sum, cat) => sum + (cat.score * cat.weight) / 100, 0);
};

// Component-level quality data
export interface ComponentData {
  id: string;
  name: string;
  group: string;
  qualityScore: number;
  trend: 'up' | 'down' | 'stable';
  history: { month: string; value: number }[];
}

const generateHistory = (base: number, volatility: number): { month: string; value: number }[] => {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  let value = base - volatility * 3;
  return months.map(month => {
    value = Math.min(100, Math.max(30, value + (Math.random() - 0.3) * volatility));
    return { month, value: Math.round(value * 10) / 10 };
  });
};

export const travelComponents: ComponentData[] = [
  // Booking & Reservation
  { id: 'flight-search', name: 'Flight Search Engine', group: 'Booking & Reservation', qualityScore: 87, trend: 'up', history: generateHistory(87, 3) },
  { id: 'hotel-search', name: 'Hotel Search Engine', group: 'Booking & Reservation', qualityScore: 82, trend: 'up', history: generateHistory(82, 4) },
  { id: 'car-rental', name: 'Car Rental Booking', group: 'Booking & Reservation', qualityScore: 78, trend: 'stable', history: generateHistory(78, 3) },
  { id: 'cruise-booking', name: 'Cruise Booking', group: 'Booking & Reservation', qualityScore: 71, trend: 'down', history: generateHistory(71, 5) },
  { id: 'package-builder', name: 'Package Builder', group: 'Booking & Reservation', qualityScore: 75, trend: 'up', history: generateHistory(75, 4) },
  { id: 'seat-selection', name: 'Seat Selection', group: 'Booking & Reservation', qualityScore: 90, trend: 'up', history: generateHistory(90, 2) },
  { id: 'ancillary-services', name: 'Ancillary Services', group: 'Booking & Reservation', qualityScore: 84, trend: 'stable', history: generateHistory(84, 3) },
  { id: 'multi-city', name: 'Multi-City Itinerary', group: 'Booking & Reservation', qualityScore: 68, trend: 'down', history: generateHistory(68, 5) },

  // Pricing & Revenue
  { id: 'fare-engine', name: 'Fare Calculation Engine', group: 'Pricing & Revenue', qualityScore: 91, trend: 'up', history: generateHistory(91, 2) },
  { id: 'pricing-rules', name: 'Pricing Rules Engine', group: 'Pricing & Revenue', qualityScore: 85, trend: 'stable', history: generateHistory(85, 3) },
  { id: 'tax-calculator', name: 'Tax & Fee Calculator', group: 'Pricing & Revenue', qualityScore: 93, trend: 'up', history: generateHistory(93, 2) },
  { id: 'currency-converter', name: 'Currency Converter', group: 'Pricing & Revenue', qualityScore: 88, trend: 'stable', history: generateHistory(88, 2) },
  { id: 'commission-engine', name: 'Commission Engine', group: 'Pricing & Revenue', qualityScore: 79, trend: 'up', history: generateHistory(79, 4) },

  // Payment & Billing
  { id: 'payment-gateway', name: 'Payment Gateway', group: 'Payment & Billing', qualityScore: 94, trend: 'up', history: generateHistory(94, 2) },
  { id: 'invoicing', name: 'Invoicing System', group: 'Payment & Billing', qualityScore: 86, trend: 'stable', history: generateHistory(86, 3) },
  { id: 'refund-engine', name: 'Refund Processing', group: 'Payment & Billing', qualityScore: 76, trend: 'down', history: generateHistory(76, 5) },
  { id: 'credit-management', name: 'Credit Management', group: 'Payment & Billing', qualityScore: 80, trend: 'up', history: generateHistory(80, 3) },

  // Customer Management
  { id: 'profile-manager', name: 'Traveler Profile Manager', group: 'Customer Management', qualityScore: 83, trend: 'up', history: generateHistory(83, 3) },
  { id: 'loyalty-program', name: 'Loyalty Program', group: 'Customer Management', qualityScore: 77, trend: 'stable', history: generateHistory(77, 4) },
  { id: 'corporate-accounts', name: 'Corporate Accounts', group: 'Customer Management', qualityScore: 81, trend: 'up', history: generateHistory(81, 3) },
  { id: 'travel-policy', name: 'Travel Policy Engine', group: 'Customer Management', qualityScore: 74, trend: 'down', history: generateHistory(74, 4) },

  // Integration & Connectivity
  { id: 'gds-connector', name: 'GDS Connector', group: 'Integration & Connectivity', qualityScore: 89, trend: 'up', history: generateHistory(89, 2) },
  { id: 'ndc-gateway', name: 'NDC Gateway', group: 'Integration & Connectivity', qualityScore: 72, trend: 'up', history: generateHistory(72, 5) },
  { id: 'hotel-aggregator', name: 'Hotel Aggregator', group: 'Integration & Connectivity', qualityScore: 80, trend: 'stable', history: generateHistory(80, 3) },
  { id: 'api-gateway', name: 'API Gateway', group: 'Integration & Connectivity', qualityScore: 92, trend: 'up', history: generateHistory(92, 2) },
  { id: 'supplier-hub', name: 'Supplier Hub', group: 'Integration & Connectivity', qualityScore: 85, trend: 'stable', history: generateHistory(85, 3) },

  // Operations & Support
  { id: 'queue-manager', name: 'Queue Manager', group: 'Operations & Support', qualityScore: 81, trend: 'up', history: generateHistory(81, 3) },
  { id: 'ticketing-engine', name: 'Ticketing Engine', group: 'Operations & Support', qualityScore: 88, trend: 'up', history: generateHistory(88, 2) },
  { id: 'pnr-manager', name: 'PNR Manager', group: 'Operations & Support', qualityScore: 86, trend: 'stable', history: generateHistory(86, 3) },
  { id: 'schedule-change', name: 'Schedule Change Handler', group: 'Operations & Support', qualityScore: 70, trend: 'down', history: generateHistory(70, 5) },
  { id: 'notification-engine', name: 'Notification Engine', group: 'Operations & Support', qualityScore: 83, trend: 'up', history: generateHistory(83, 3) },

  // Reporting & Analytics
  { id: 'mis-reporting', name: 'MIS Reporting', group: 'Reporting & Analytics', qualityScore: 79, trend: 'up', history: generateHistory(79, 4) },
  { id: 'bi-dashboard', name: 'BI Dashboard', group: 'Reporting & Analytics', qualityScore: 82, trend: 'up', history: generateHistory(82, 3) },
  { id: 'data-warehouse', name: 'Data Warehouse', group: 'Reporting & Analytics', qualityScore: 76, trend: 'stable', history: generateHistory(76, 4) },

  // Security & Compliance
  { id: 'auth-service', name: 'Authentication Service', group: 'Security & Compliance', qualityScore: 95, trend: 'up', history: generateHistory(95, 1) },
  { id: 'pci-compliance', name: 'PCI Compliance Module', group: 'Security & Compliance', qualityScore: 92, trend: 'stable', history: generateHistory(92, 2) },
  { id: 'gdpr-engine', name: 'GDPR Engine', group: 'Security & Compliance', qualityScore: 89, trend: 'up', history: generateHistory(89, 2) },
  { id: 'fraud-detection', name: 'Fraud Detection', group: 'Security & Compliance', qualityScore: 87, trend: 'up', history: generateHistory(87, 3) },

  // User Interface
  { id: 'web-frontend', name: 'Web Frontend', group: 'User Interface', qualityScore: 84, trend: 'up', history: generateHistory(84, 3) },
  { id: 'mobile-app', name: 'Mobile App', group: 'User Interface', qualityScore: 78, trend: 'up', history: generateHistory(78, 4) },
  { id: 'agent-desktop', name: 'Agent Desktop', group: 'User Interface', qualityScore: 73, trend: 'stable', history: generateHistory(73, 4) },
];
